import re
res = {u'context': {u'title': u'Imdb'},
 u'items': [{u'cacheId': u'IMSVHNt8c5gJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/title/tt2481138/',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/title/tt2481138/',
             u'htmlSnippet': u'Directed by <b>Shaz Bennett</b>. With Martin L. Washington Jr., Spencer Broschard, <br>\nBarret Lewis, Bernard Addison. Leo&#39;s dreams of being an international superstar<br>\n&nbsp;...',
             u'htmlTitle': u'<b>Alaska Is a Drag</b> (2012) - <b>IMDb</b>',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/title/tt2481138/',
             u'pagemap': {u'aggregaterating': [{u'bestrating': u'10',
                                                u'ratingcount': u'80',
                                                u'ratingvalue': u'6.6',
                                                u'reviewcount': u'5 critic'}],
                          u'cse_image': [{u'src': u'http://ia.media-imdb.com/images/M/MV5BMjE5MTIwMjgwM15BMl5BanBnXkFtZTcwNDA4MTE2OA@@._V1_UY190_CR0,0,128,190_AL_.jpg'}],
                          u'cse_thumbnail': [{u'height': u'152',
                                              u'src': u'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR8xG6cT6DwsavdEpWkJVZdRU62xyeoQVGhGogTbybXD6Xh4X7jn3MV2Ec',
                                              u'width': u'102'}],
                          u'hcard': [{u'fn': u'Shaz Bennett',
                                      u'url': u'http://www.imdb.com/name/nm0072062?ref_=tt_ov_dr'},
                                     {u'fn': u'Shaz Bennett',
                                      u'url': u'http://www.imdb.com/name/nm0072062?ref_=tt_ov_wr'},
                                     {u'fn': u'Martin L. Washington Jr.',
                                      u'url': u'http://www.imdb.com/name/nm5165550?ref_=tt_ov_st_sm'},
                                     {u'fn': u'Spencer Broschard',
                                      u'url': u'http://www.imdb.com/name/nm5319072?ref_=tt_ov_st_sm'},
                                     {u'fn': u'Barret Lewis',
                                      u'url': u'http://www.imdb.com/name/nm4447253?ref_=tt_ov_st_sm'},
                                     {u'fn': u'Martin L. Washington Jr.',
                                      u'url': u'http://www.imdb.com/name/nm5165550/?ref_=tt_cl_t1'},
                                     {u'fn': u'Spencer Broschard',
                                      u'url': u'http://www.imdb.com/name/nm5319072/?ref_=tt_cl_t2'},
                                     {u'fn': u'Barret Lewis',
                                      u'url': u'http://www.imdb.com/name/nm4447253/?ref_=tt_cl_t3'},
                                     {u'fn': u'Bernard Addison',
                                      u'url': u'http://www.imdb.com/name/nm0011698/?ref_=tt_cl_t4'},
                                     {u'fn': u'Jill Morley',
                                      u'url': u'http://www.imdb.com/name/nm0605896/?ref_=tt_cl_t5'},
                                     {u'fn': u'Jason Jaworski',
                                      u'url': u'http://www.imdb.com/name/nm3756577/?ref_=tt_cl_t6'},
                                     {u'fn': u'Sonya Karels',
                                      u'url': u'http://www.imdb.com/name/nm5443240/?ref_=tt_cl_t7'}],
                          u'metatags': [{u'apple-itunes-app': u'app-id=342792525, app-argument=imdb:///title/tt2481138?src=mdot',
                                         u'fb:app_id': u'115109575169727',
                                         u'og:description': u"Directed by Shaz Bennett.  With Martin L. Washington Jr., Spencer Broschard, Barret Lewis, Bernard Addison. Leo's dreams of being an international superstar are hard fought working in a fish cannery in Alaska.",
                                         u'og:image': u'http://ia.media-imdb.com/images/G/01/imdb/images/logos/imdb_fb_logo-1730868325._CB306318125_.png',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Alaska Is a Drag (2012)',
                                         u'og:type': u'video.movie',
                                         u'og:url': u'http://www.imdb.com/title/tt2481138/',
                                         u'pageid': u'tt2481138',
                                         u'pagetype': u'title',
                                         u'request_id': u'1RK1S5S4QQYE3RJJ340E',
                                         u'subpagetype': u'main',
                                         u'theme-color': u'#000000',
                                         u'title': u'Alaska Is a Drag (2012) - IMDb'}],
                          u'person': [{u'name': u'Shaz Bennett',
                                       u'url': u'Shaz Bennett'},
                                      {u'name': u'Shaz Bennett',
                                       u'url': u'Shaz Bennett'},
                                      {u'name': u'Martin L. Washington Jr.',
                                       u'url': u'Martin L. Washington Jr.'},
                                      {u'name': u'Spencer Broschard',
                                       u'url': u'Spencer Broschard'},
                                      {u'name': u'Barret Lewis',
                                       u'url': u'Barret Lewis'},
                                      {u'name': u'Martin L. Washington Jr.',
                                       u'url': u'Martin L. Washington Jr.'},
                                      {u'name': u'Spencer Broschard',
                                       u'url': u'Spencer Broschard'},
                                      {u'name': u'Barret Lewis',
                                       u'url': u'Barret Lewis'},
                                      {u'name': u'Bernard Addison',
                                       u'url': u'Bernard Addison'},
                                      {u'name': u'Jill Morley',
                                       u'url': u'Jill Morley'},
                                      {u'name': u'Jason Jaworski',
                                       u'url': u'Jason Jaworski'},
                                      {u'name': u'Sonya Karels',
                                       u'url': u'Sonya Karels'}]},
             u'snippet': u"Directed by Shaz Bennett. With Martin L. Washington Jr., Spencer Broschard, \nBarret Lewis, Bernard Addison. Leo's dreams of being an international superstar\n\xa0...",
             u'title': u'Alaska Is a Drag (2012) - IMDb'},
            {u'cacheId': u'aCErbxzujWgJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/title/tt4341390/',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/title/tt4341390/',
             u'htmlSnippet': u'Directed by <b>Shaz Bennett</b>. With Martin L. Washington Jr., Maya Washington, Matt <br>\nDallas, Christopher O&#39;Shea. If ROCKY and HEDWIG had a love child - that&nbsp;...',
             u'htmlTitle': u'<b>Alaska Is a Drag</b> (2016) - <b>IMDb</b>',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/title/tt4341390/',
             u'pagemap': {u'cse_image': [{u'src': u'http://ia.media-imdb.com/images/G/01/imdb/images/logos/imdb_fb_logo-1730868325._CB306318125_.png'}],
                          u'metatags': [{u'apple-itunes-app': u'app-id=342792525, app-argument=imdb:///title/tt4341390?src=mdot',
                                         u'fb:app_id': u'115109575169727',
                                         u'og:description': u"Directed by Shaz Bennett.  With Martin L. Washington Jr., Maya Washington, Matt Dallas, Christopher O'Shea. If ROCKY and HEDWIG had a love child - that would best describe our hero LEO -- an aspiring superstar - if he can just get out of Alaska. Everyone who works in a fish cannery - slicing fish for 14 hours a day -- dreams of a better life. Leo's dreams are just a little more glamstastic than most.",
                                         u'og:image': u'http://ia.media-imdb.com/images/G/01/imdb/images/logos/imdb_fb_logo-1730868325._CB306318125_.png',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Alaska Is a Drag (2016)',
                                         u'og:type': u'video.movie',
                                         u'og:url': u'http://www.imdb.com/title/tt4341390/',
                                         u'pageid': u'tt4341390',
                                         u'pagetype': u'title',
                                         u'request_id': u'1Y05MH0FMTCAXZ4FVQQD',
                                         u'subpagetype': u'main',
                                         u'theme-color': u'#000000',
                                         u'title': u'Alaska Is a Drag (2016) - IMDb'}],
                          u'movie': [{u'description': u'If ROCKY and HEDWIG had a love child - that would best describe our hero LEO -- an aspiring superstar - if he can just get out of Alaska. Everyone who works in a fish cannery - slicing fish......',
                                      u'genre': u'Drama',
                                      u'image': u'http://ia.media-imdb.com/images/M/MV5BMjUwNDkxMjcyMV5BMl5BanBnXkFtZTcwODUyMDMyNw@@._UY450_CR200,80,307,230_SY230_SX307_AL_.jpg',
                                      u'name': u'Alaska Is a Drag (2016)',
                                      u'url': u'in-production titles'}],
                          u'moviereview': [{u'directed_by': u'Shaz Bennett',
                                            u'genre': u'Drama/Genres: Drama',
                                            u'image_href': u'http://ia.media-imdb.com/images/G/01/imdb/images/widget/amazon._CB339202444_.png',
                                            u'name': u'Alaska Is a Drag (2016)',
                                            u'starring': u'Martin L. Washington Jr., Maya Washington, Matt Dallas',
                                            u'summary': u'If ROCKY and HEDWIG had a love child - that would best describe our hero LEO -- an aspiring superstar - if he can just get out of Alaska. Everyone who...'}],
                          u'organization': [{u'name': u'Fishbowl Films',
                                             u'url': u'Fishbowl Films'}],
                          u'person': [{u'name': u'Shaz Bennett',
                                       u'url': u'Shaz Bennett'},
                                      {u'name': u'Shaz Bennett',
                                       u'url': u'Shaz Bennett'},
                                      {u'name': u'Martin L. Washington Jr.',
                                       u'url': u'Martin L. Washington Jr.'},
                                      {u'name': u'Maya Washington',
                                       u'url': u'Maya Washington'},
                                      {u'name': u'Matt Dallas',
                                       u'url': u'Matt Dallas'},
                                      {u'name': u'Martin L. Washington Jr.',
                                       u'url': u'Martin L. Washington Jr.'},
                                      {u'name': u'Maya Washington',
                                       u'url': u'Maya Washington'},
                                      {u'name': u'Matt Dallas',
                                       u'url': u'Matt Dallas'},
                                      {u'name': u"Christopher O'Shea",
                                       u'url': u"Christopher O'Shea"},
                                      {u'name': u'Jason Scott Lee',
                                       u'url': u'Jason Scott Lee'},
                                      {u'name': u'Margaret Cho',
                                       u'url': u'Margaret Cho'},
                                      {u'name': u'Kevin Daniels',
                                       u'url': u'Kevin Daniels'},
                                      {u'name': u'John Fleck',
                                       u'url': u'John Fleck'},
                                      {u'name': u'Nia Peeples',
                                       u'url': u'Nia Peeples'},
                                      {u'name': u'Adam Tomei',
                                       u'url': u'Adam Tomei'},
                                      {u'name': u'Tim Holmes',
                                       u'url': u'Tim Holmes'},
                                      {u'name': u'Connie Kincer',
                                       u'url': u'Connie Kincer'},
                                      {u'name': u'Jennifer Jelsema',
                                       u'url': u'Jennifer Jelsema'},
                                      {u'name': u'Matt Hudson',
                                       u'url': u'Matt Hudson'}]},
             u'snippet': u"Directed by Shaz Bennett. With Martin L. Washington Jr., Maya Washington, Matt \nDallas, Christopher O'Shea. If ROCKY and HEDWIG had a love child - that\xa0...",
             u'title': u'Alaska Is a Drag (2016) - IMDb'},
            {u'cacheId': u'HPioKV636PoJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/name/nm0072062/',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/name/nm0072062/',
             u'htmlSnippet': u'<b>Shaz Bennett</b>, Writer: <b>Alaska Is a Drag</b>. Shaz is a writer, director, storyteller. On <br>\nher way to being a full time filmmaker and writer of television - Shaz worked in a&nbsp;...',
             u'htmlTitle': u'<b>Shaz Bennett</b> - <b>IMDb</b>',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/name/nm0072062/',
             u'pagemap': {u'cse_image': [{u'src': u'http://ia.media-imdb.com/images/M/MV5BMjQwMTY5MjUzOV5BMl5BanBnXkFtZTgwOTQ3NTQ5MTE@._V1_UY1200_CR530,0,630,1200_AL_.jpg'}],
                          u'cse_thumbnail': [{u'height': u'310',
                                              u'src': u'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcREm1OJVlhLV8NwHG2f5sWo86bqBj1I-CKgyW8A2YIj3Qjzo3i-jMfdEVA_',
                                              u'width': u'163'}],
                          u'hcard': [{u'fn': u'Shaz Bennett',
                                      u'photo': u'http://ia.media-imdb.com/images/G/01/imdb/images/nopicture/small/no-video-slate-856072904._CB379390253_.png',
                                      u'title': u'Miscellaneous Crew',
                                      u'url': u'http://www.imdb.com/offsite/?page-action=offsite-shazbennett&token=BCYrx4g6mea52s5vjQ1d6OA5dcakhePZI_inNLPt-rvRZo-YKXlbluaPJS3unU3HiXHzxCHdSk7N%0D%0AUkrGgVL1LMdVeR03CpVl-KPJ3wQiqM4PxoscWiKDdqMO1jydOMSfcxVFWeWfNms-7UQrjTTH3hwk%0D%0AsZGsyu3rb0g6nNSUt_Pli0zGfK8pdBpBYipCvGGn6RRJuz0GTw2OeLmnCl3jQuQrO4x7SzF5Afr3%0D%0AjCGcTl2etg0%0D%0A&ref_=nm_pdt_ofs_offsite_0'}],
                          u'metatags': [{u'apple-itunes-app': u'app-id=342792525, app-argument=imdb:///name/nm0072062?src=mdot',
                                         u'fb:app_id': u'115109575169727',
                                         u'og:description': u"Shaz Bennett, Writer: Alaska Is a Drag. Shaz is a writer, director, storyteller. On her way to being a full time filmmaker and writer of television -\xad Shaz worked in a fish cannery; bartended at a mafia bar; was a film programmer at Sundance, LA Film Festival and AFI FEST; peddled liquor undercover; developed films for actor Giancarlo Esposito; and was Cher's stand-in for a day. Her films and performance pieces have been seen in ...",
                                         u'og:image': u'http://ia.media-imdb.com/images/M/MV5BMjQwMTY5MjUzOV5BMl5BanBnXkFtZTgwOTQ3NTQ5MTE@._V1_UY1200_CR530,0,630,1200_AL_.jpg',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Shaz Bennett',
                                         u'og:type': u'actor',
                                         u'og:url': u'http://www.imdb.com/name/nm0072062/',
                                         u'pageid': u'nm0072062',
                                         u'pagetype': u'name',
                                         u'request_id': u'0YY9VZ0DS3VTMTZGJF3D',
                                         u'subpagetype': u'main',
                                         u'theme-color': u'#000000',
                                         u'title': u'Shaz Bennett - IMDb'}],
                          u'person': [{u'role': u'Miscellaneous Crew'},
                                      {u'awards': u'1 nomination.',
                                       u'datepublished': u'23 November 2015 2:30 PM, -05:00',
                                       u'description': u'Shaz is a writer, director, storyteller. On her way to being a full time filmmaker and writer of television - Shaz worked in a fish cannery; bartended at a mafia bar; was a film programmer...',
                                       u'headline': u'2016 Sundance Film Festival Predictions: Carson Mell\u2019s Another Evil',
                                       u'image': u'http://ia.media-imdb.com/images/M/MV5BMjQwMTY5MjUzOV5BMl5BanBnXkFtZTgwOTQ3NTQ5MTE@._V1_UY317_CR116,0,214,317_AL_.jpg',
                                       u'jobtitle': u'Miscellaneous Crew',
                                       u'name': u'Shaz Bennett',
                                       u'provider': u'ioncinema',
                                       u'thumbnailurl': u'http://www.imdb.com/media/rm1752506112/nm0072062?ref_=nm_phs_md_1',
                                       u'url': u'Watch Now'}]},
             u'snippet': u'Shaz Bennett, Writer: Alaska Is a Drag. Shaz is a writer, director, storyteller. On \nher way to being a full time filmmaker and writer of television - Shaz worked in a\xa0...',
             u'title': u'Shaz Bennett - IMDb'},
            {u'cacheId': u'y72BEk-OULwJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/title/tt4831810/news?year=2015&ref_=tt...3',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/title/tt4831810/news?year=2015&amp;ref_=tt...3',
             u'htmlSnippet': u'The Loner on <b>IMDb</b>: Movies, TV, Celebs, and more...',
             u'htmlTitle': u'&#39;<b>Alaska is a Drag</b>&#39; by <b>Shaz Bennett</b> and Producers Diane Becker and <b>...</b>',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/title/tt4831810/news?year=2015&ref_=tt_nwr_3',
             u'pagemap': {u'metatags': [{u'application-name': u'IMDb',
                                         u'fb:app_id': u'115109575169727',
                                         u'msapplication-task': u'name=Find Movie Showtimes;action-uri=/showtimes/;icon-uri=http://i.media-imdb.com/images/SFff39adb4d259f3c3fd166853a6714a32/favicon.ico',
                                         u'msapplication-tooltip': u'IMDb Web App',
                                         u'msapplication-window': u'width=1500;height=900',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'The Loner (2016) - News',
                                         u'og:url': u'http://www.imdb.com/title/tt4831810/news?year=2015&',
                                         u'title': u'The Loner (2016) - News'}]},
             u'snippet': u'The Loner on IMDb: Movies, TV, Celebs, and more...',
             u'title': u"'Alaska is a Drag' by Shaz Bennett and Producers Diane Becker and ..."},
            {u'cacheId': u'q9oim7PqXFkJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/name/nm0072062/bio',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/name/nm0072062/bio',
             u'htmlSnippet': u'On her way to being a full time filmmaker and writer of television - <b>Shaz</b> worked in <br>\na ... Malone award, where she made the award winning film <b>Alaska is a Drag</b>.',
             u'htmlTitle': u'<b>Shaz Bennett</b> - Biography - <b>IMDb</b>',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/name/nm0072062/bio',
             u'pagemap': {u'cse_image': [{u'src': u'http://ia.media-imdb.com/images/M/MV5BMjQwMTY5MjUzOV5BMl5BanBnXkFtZTgwOTQ3NTQ5MTE@._V1_UY1200_CR530,0,630,1200_AL_.jpg'}],
                          u'cse_thumbnail': [{u'height': u'310',
                                              u'src': u'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcREm1OJVlhLV8NwHG2f5sWo86bqBj1I-CKgyW8A2YIj3Qjzo3i-jMfdEVA_',
                                              u'width': u'163'}],
                          u'metatags': [{u'fb:app_id': u'115109575169727',
                                         u'og:description': u'Shaz is a writer, director, storyteller. On her way to being a full time filmmaker and writer of television -\xad Shaz worked in a fish cannery; ...',
                                         u'og:image': u'http://ia.media-imdb.com/images/M/MV5BMjQwMTY5MjUzOV5BMl5BanBnXkFtZTgwOTQ3NTQ5MTE@._V1_UY1200_CR530,0,630,1200_AL_.jpg',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Shaz Bennett',
                                         u'og:type': u'actor',
                                         u'og:url': u'http://www.imdb.com/name/nm0072062/bio',
                                         u'request_id': u'0Y6A157330KV1BZ040CG',
                                         u'theme-color': u'#000000',
                                         u'title': u'Shaz Bennett - IMDb'}]},
             u'snippet': u'On her way to being a full time filmmaker and writer of television - Shaz worked in \na ... Malone award, where she made the award winning film Alaska is a Drag.',
             u'title': u'Shaz Bennett - Biography - IMDb'},
            {u'cacheId': u'dNbjc501bWUJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/title/tt3662778/news',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/title/tt3662778/news',
             u'htmlSnippet': u'Americana on <b>IMDb</b>: Movies, TV, Celebs, and more... ... Movie is Delusional in a <br>\nWay\u201d: <b>Alaska is a Drag</b>&#39;s <b>Shaz Bennett</b> and Melanie Miller at Us in Progress.',
             u'htmlTitle': u'Americana (????/II) - News',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/title/tt3662778/news',
             u'pagemap': {u'metatags': [{u'application-name': u'IMDb',
                                         u'fb:app_id': u'115109575169727',
                                         u'msapplication-task': u'name=Find Movie Showtimes;action-uri=/showtimes/;icon-uri=http://i.media-imdb.com/images/SFff39adb4d259f3c3fd166853a6714a32/favicon.ico',
                                         u'msapplication-tooltip': u'IMDb Web App',
                                         u'msapplication-window': u'width=1500;height=900',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Americana (????/II) - News',
                                         u'og:url': u'http://www.imdb.com/title/tt3662778/news',
                                         u'title': u'Americana (????/II) - News'}]},
             u'snippet': u"Americana on IMDb: Movies, TV, Celebs, and more... ... Movie is Delusional in a \nWay\u201d: Alaska is a Drag's Shaz Bennett and Melanie Miller at Us in Progress.",
             u'title': u'Americana (????/II) - News'},
            {u'cacheId': u'0XbyDtQJ0WMJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/title/tt4341390/combined',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/title/tt4341390/combined',
             u'htmlSnippet': u'Directed by <b>Shaz Bennett</b>. With Martin L. Washington Jr., Maya Washington, Matt <br>\nDallas. Visit <b>IMDb</b> for Photos, Showtimes, <b>Cast</b>, Crew, Reviews, Plot Summary,&nbsp;...',
             u'htmlTitle': u'<b>Alaska Is a Drag</b> (2016)',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/title/tt4341390/combined',
             u'pagemap': {u'cse_image': [{u'src': u'http://i.media-imdb.com/images/SF007a3f88c795cfb71af4856df1fb5fee/imdb-share-logo.png'}],
                          u'metatags': [{u'application-name': u'IMDb',
                                         u'fb:app_id': u'115109575169727',
                                         u'msapplication-task': u'name=Find Movie Showtimes;action-uri=/showtimes/;icon-uri=http://i.media-imdb.com/images/SFff39adb4d259f3c3fd166853a6714a32/favicon.ico',
                                         u'msapplication-tooltip': u'IMDb Web App',
                                         u'msapplication-window': u'width=1500;height=900',
                                         u'og:image': u'http://i.media-imdb.com/images/SF007a3f88c795cfb71af4856df1fb5fee/imdb-share-logo.png',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Alaska Is a Drag (2016)',
                                         u'og:type': u'movie',
                                         u'og:url': u'http://www.imdb.com/title/tt4341390/combined',
                                         u'title': u'Alaska Is a Drag (2016)'}]},
             u'snippet': u'Directed by Shaz Bennett. With Martin L. Washington Jr., Maya Washington, Matt \nDallas. Visit IMDb for Photos, Showtimes, Cast, Crew, Reviews, Plot Summary,\xa0...',
             u'title': u'Alaska Is a Drag (2016)'},
            {u'cacheId': u'eH_jpQ0CIUgJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/title/tt2481138/fullcredits/',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/title/tt2481138/fullcredits/',
             u'htmlSnippet': u'<b>Alaska Is a Drag</b> (2012) <b>cast</b> and crew credits, including actors, actresses, <br>\ndirectors, writers and more. ... <b>Shaz Bennett</b> ... Rest of <b>cast</b> listed alphabetically:.',
             u'htmlTitle': u'<b>Alaska Is a Drag</b> (2012) - Full <b>Cast</b> &amp; Crew - <b>IMDb</b>',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/title/tt2481138/fullcredits/',
             u'pagemap': {u'cse_image': [{u'src': u'http://ia.media-imdb.com/images/G/01/imdb/images/logos/imdb_fb_logo-1730868325._CB306318125_.png'}],
                          u'hcard': [{u'fn': u'Martin L. Washington Jr.',
                                      u'url': u'http://www.imdb.com/name/nm5165550/?ref_=ttfc_fc_cl_t1'},
                                     {u'fn': u'Spencer Broschard',
                                      u'url': u'http://www.imdb.com/name/nm5319072/?ref_=ttfc_fc_cl_t2'},
                                     {u'fn': u'Barret Lewis',
                                      u'url': u'http://www.imdb.com/name/nm4447253/?ref_=ttfc_fc_cl_t3'},
                                     {u'fn': u'Bernard Addison',
                                      u'url': u'http://www.imdb.com/name/nm0011698/?ref_=ttfc_fc_cl_t4'},
                                     {u'fn': u'Jill Morley',
                                      u'url': u'http://www.imdb.com/name/nm0605896/?ref_=ttfc_fc_cl_t5'},
                                     {u'fn': u'Jason Jaworski',
                                      u'url': u'http://www.imdb.com/name/nm3756577/?ref_=ttfc_fc_cl_t6'},
                                     {u'fn': u'Sonya Karels',
                                      u'url': u'http://www.imdb.com/name/nm5443240/?ref_=ttfc_fc_cl_t7'}],
                          u'metatags': [{u'apple-itunes-app': u'app-id=342792525, app-argument=imdb:///title/tt2481138?src=mdot',
                                         u'fb:app_id': u'115109575169727',
                                         u'og:description': u'Alaska Is a Drag (2012) cast and crew credits, including actors, actresses, directors, writers and more.',
                                         u'og:image': u'http://ia.media-imdb.com/images/G/01/imdb/images/logos/imdb_fb_logo-1730868325._CB306318125_.png',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Alaska Is a Drag (2012)',
                                         u'og:type': u'video.movie',
                                         u'og:url': u'http://www.imdb.com/title/tt2481138/fullcredits/',
                                         u'pageid': u'tt2481138',
                                         u'pagetype': u'title',
                                         u'request_id': u'1SR02G72C5VXYJS31PMR',
                                         u'subpagetype': u'fullcredits',
                                         u'theme-color': u'#000000',
                                         u'title': u'Alaska Is a Drag (2012) - IMDb'}],
                          u'person': [{u'name': u'Martin L. Washington Jr.',
                                       u'url': u'Martin L. Washington Jr.'},
                                      {u'name': u'Spencer Broschard',
                                       u'url': u'Spencer Broschard'},
                                      {u'name': u'Barret Lewis',
                                       u'url': u'Barret Lewis'},
                                      {u'name': u'Bernard Addison',
                                       u'url': u'Bernard Addison'},
                                      {u'name': u'Jill Morley',
                                       u'url': u'Jill Morley'},
                                      {u'name': u'Jason Jaworski',
                                       u'url': u'Jason Jaworski'},
                                      {u'name': u'Sonya Karels',
                                       u'url': u'Sonya Karels'}]},
             u'snippet': u'Alaska Is a Drag (2012) cast and crew credits, including actors, actresses, \ndirectors, writers and more. ... Shaz Bennett ... Rest of cast listed alphabetically:.',
             u'title': u'Alaska Is a Drag (2012) - Full Cast & Crew - IMDb'},
            {u'cacheId': u'CADYXkzXjPcJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/title/tt4341390/fullcredits/',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/title/tt4341390/fullcredits/',
             u'htmlSnippet': u'<b>Alaska Is a Drag</b> (2016) <b>cast</b> and crew credits, including actors, actresses, <br>\ndirectors, writers and more. ... <b>Shaz Bennett</b>. Writing Credits (in alphabetical order<br>\n)&nbsp;...',
             u'htmlTitle': u'<b>Alaska Is a Drag</b> (2016) - Full <b>Cast</b> &amp; Crew - <b>IMDb</b>',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/title/tt4341390/fullcredits/',
             u'pagemap': {u'cse_image': [{u'src': u'http://ia.media-imdb.com/images/G/01/imdb/images/logos/imdb_fb_logo-1730868325._CB306318125_.png'}],
                          u'metatags': [{u'apple-itunes-app': u'app-id=342792525, app-argument=imdb:///title/tt4341390?src=mdot',
                                         u'fb:app_id': u'115109575169727',
                                         u'og:description': u'Alaska Is a Drag (2016) cast and crew credits, including actors, actresses, directors, writers and more.',
                                         u'og:image': u'http://ia.media-imdb.com/images/G/01/imdb/images/logos/imdb_fb_logo-1730868325._CB306318125_.png',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Alaska Is a Drag (2016)',
                                         u'og:type': u'video.movie',
                                         u'og:url': u'http://www.imdb.com/title/tt4341390/fullcredits/',
                                         u'pageid': u'tt4341390',
                                         u'pagetype': u'title',
                                         u'request_id': u'1456CG12BE1H5GN1J8BZ',
                                         u'subpagetype': u'fullcredits',
                                         u'theme-color': u'#000000',
                                         u'title': u'Alaska Is a Drag (2016) - IMDb'}],
                          u'movie': [{u'name': u'Alaska Is a Drag (2016)',
                                      u'url': u'Alaska Is a Drag'}],
                          u'moviereview': [{u'name': u'Alaska Is a Drag (2016)',
                                            u'starring': u'Martin L. Washington Jr., Maya Washington, Matt Dallas'}],
                          u'person': [{u'name': u'Martin L. Washington Jr.',
                                       u'url': u'Martin L. Washington Jr.'},
                                      {u'name': u'Maya Washington',
                                       u'url': u'Maya Washington'},
                                      {u'name': u'Matt Dallas',
                                       u'url': u'Matt Dallas'},
                                      {u'name': u"Christopher O'Shea",
                                       u'url': u"Christopher O'Shea"},
                                      {u'name': u'Jason Scott Lee',
                                       u'url': u'Jason Scott Lee'},
                                      {u'name': u'Margaret Cho',
                                       u'url': u'Margaret Cho'},
                                      {u'name': u'Kevin Daniels',
                                       u'url': u'Kevin Daniels'},
                                      {u'name': u'John Fleck',
                                       u'url': u'John Fleck'},
                                      {u'name': u'Nia Peeples',
                                       u'url': u'Nia Peeples'},
                                      {u'name': u'Adam Tomei',
                                       u'url': u'Adam Tomei'},
                                      {u'name': u'Tim Holmes',
                                       u'url': u'Tim Holmes'},
                                      {u'name': u'Jennifer Jelsema',
                                       u'url': u'Jennifer Jelsema'},
                                      {u'name': u'Connie Kincer',
                                       u'url': u'Connie Kincer'},
                                      {u'name': u'Matt Hudson',
                                       u'url': u'Matt Hudson'}]},
             u'snippet': u'Alaska Is a Drag (2016) cast and crew credits, including actors, actresses, \ndirectors, writers and more. ... Shaz Bennett. Writing Credits (in alphabetical order\n)\xa0...',
             u'title': u'Alaska Is a Drag (2016) - Full Cast & Crew - IMDb'},
            {u'cacheId': u'FPxXCcJPHscJ',
             u'displayLink': u'www.imdb.com',
             u'formattedUrl': u'www.imdb.com/name/nm0072062/awards',
             u'htmlFormattedUrl': u'www.<b>imdb</b>.com/name/nm0072062/awards',
             u'htmlSnippet': u'<b>Shaz Bennett</b> on <b>IMDb</b>: Awards, nominations, and wins. ... 2012, Nominated <br>\nGrand Jury Prize, Live Action Short Film <b>Alaska Is a Drag</b> (2012)&nbsp;...',
             u'htmlTitle': u'<b>Shaz Bennett</b> - Awards - <b>IMDb</b>',
             u'kind': u'customsearch#result',
             u'link': u'http://www.imdb.com/name/nm0072062/awards',
             u'pagemap': {u'cse_image': [{u'src': u'http://ia.media-imdb.com/images/M/MV5BMjQwMTY5MjUzOV5BMl5BanBnXkFtZTgwOTQ3NTQ5MTE@._V1_UY1200_CR530,0,630,1200_AL_.jpg'}],
                          u'cse_thumbnail': [{u'height': u'310',
                                              u'src': u'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcREm1OJVlhLV8NwHG2f5sWo86bqBj1I-CKgyW8A2YIj3Qjzo3i-jMfdEVA_',
                                              u'width': u'163'}],
                          u'metatags': [{u'apple-itunes-app': u'app-id=342792525, app-argument=imdb:///name/nm0072062?src=mdot',
                                         u'fb:app_id': u'115109575169727',
                                         u'og:description': u'Shaz Bennett on IMDb: Awards, nominations, and wins',
                                         u'og:image': u'http://ia.media-imdb.com/images/M/MV5BMjQwMTY5MjUzOV5BMl5BanBnXkFtZTgwOTQ3NTQ5MTE@._V1_UY1200_CR530,0,630,1200_AL_.jpg',
                                         u'og:site_name': u'IMDb',
                                         u'og:title': u'Shaz Bennett',
                                         u'og:type': u'actor',
                                         u'og:url': u'http://www.imdb.com/name/nm0072062/awards',
                                         u'pageid': u'nm0072062',
                                         u'pagetype': u'name',
                                         u'request_id': u'04NXCVGMHYTHSGPMYQED',
                                         u'subpagetype': u'awards',
                                         u'theme-color': u'#000000',
                                         u'title': u'Shaz Bennett - IMDb'}]},
             u'snippet': u'Shaz Bennett on IMDb: Awards, nominations, and wins. ... 2012, Nominated \nGrand Jury Prize, Live Action Short Film Alaska Is a Drag (2012)\xa0...',
             u'title': u'Shaz Bennett - Awards - IMDb'}],
 u'kind': u'customsearch#search',
 u'queries': {u'nextPage': [{u'count': 10,
                             u'cx': u'009241977094486741223:3agszpaq5sy',
                             u'inputEncoding': u'utf8',
                             u'outputEncoding': u'utf8',
                             u'safe': u'off',
                             u'searchTerms': u'Alaska is a Drag imdb Shaz Bennett',
                             u'startIndex': 11,
                             u'title': u'Google Custom Search - Alaska is a Drag imdb Shaz Bennett',
                             u'totalResults': u'164'}],
              u'request': [{u'count': 10,
                            u'cx': u'009241977094486741223:3agszpaq5sy',
                            u'inputEncoding': u'utf8',
                            u'outputEncoding': u'utf8',
                            u'safe': u'off',
                            u'searchTerms': u'Alaska is a Drag imdb Shaz Bennett',
                            u'startIndex': 1,
                            u'title': u'Google Custom Search - Alaska is a Drag imdb Shaz Bennett',
                            u'totalResults': u'164'}]},
 u'searchInformation': {u'formattedSearchTime': u'0.32',
                        u'formattedTotalResults': u'164',
                        u'searchTime': 0.315625,
                        u'totalResults': u'164'},
 u'url': {u'template': u'https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&cref={cref?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json',
          u'type': u'application/json'}}


try:
	for i in range(0,len(res['items'])):
		print "===================================="
		print i
		json_title = res['items'][i]['htmlTitle']
		print json_title.encode('utf8')
		json_director =res['items'][i]['htmlSnippet']
		print json_director.encode('utf8')

		if re.search(r'Alaska Is a Drag',json_title) and re.search(r'Shaz Bennett',json_director):
			imdb_key = res['items'][i]['formattedUrl']
			imdb_key = re.search('^www.*?title/(.*?)/.*',imdb_key)
			print 'IMDB Key :: ', imdb_key.group(1)
			break
		else:
			print 'KEY NOT FOUND' 

except Exception, e:
	print "Imdb key not found",e
